### ISSUE TITLE
Robolectric

### ISSUE THREAD

**Issue by zubr1** [intuit/sdp#14]
When I'm trying to use robolectric framework with layout covered by sdp, I'm getting this error:

android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\activity_main.xml line #-1 (sorry, not yet implemented): XML file build\intermediates\res\merged\debug\layout\activity_main.xml line #-1 (sorry, not yet implemented): Error inflating class Button

	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.gmail.zubrapps.calculatedistance.MainActivity.onCreate(MainActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:6237)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:340)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
	at com.gmail.zubrapps.calculatedistance.MainActivityTest.validateTextViewContent(MainActivityTest.java:17)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:467)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:176)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:142)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: android.view.InflateException: XML file build\intermediates\res\merged\debug\layout\activity_main.xml line #-1 (sorry, not yet implemented): Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 35 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:666)
	at android.widget.TextView.__constructor__(TextView.java:1055)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.Button.<init>(Button.java)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	... 39 more

I wonder, if its because robolectric cannot know the size of device, so sdp cannot be converted to the proper dp. My question is: Is there any possibility to overcome this issue?

**Comment by elhanan-mishraky** [comment]
Unfortunately I don't know. It seems to me like a bug in Robolectric.
